services:
  - type: web
    name: sproochentest-bot
    runtime: python
    plan: free
    rootDir: bot
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.7"
      - key: BOT_TOKEN
        sync: false
